FROM python:3.10

WORKDIR /app

RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY data_preprocessing.py .
COPY front_streamlit.py .

EXPOSE 8501

CMD ["streamlit", "run", "--server.port=8501", "--server.address=0.0.0.0", "front_streamlit.py"]