FROM python:3.10

WORKDIR /app

RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"

COPY requirements.txt .
RUN pip3 install -r requirements.txt

#COPY reddit_credentials .
COPY reddit_streamer.py .

CMD ["python", "reddit_streamer.py"]