version: '3'
services:
  streamer:
    build:
      context: ./Extract
      dockerfile: Dockerfile.extract
    volumes:
      - myvolume:/app/Shared
    networks:
    - mynetwork
  data_preprocessing:
    build:
      context: ./Processing
      dockerfile: Dockerfile.data_processing
    ports:
      - 5000:5000
    volumes:
      - myvolume:/app/Shared
    networks:
      - mynetwork
  front_streamlit:
    build:
      context: ./Streamlit
      dockerfile: Dockerfile.front_streamlit
    depends_on:
      - data_processing
    ports:
      - 8501:8501
    volumes:
      - myvolume:/app/Shared
volumes:
  myvolume:
networks:
  mynetwork: