FROM python:3.10

WORKDIR /app

RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"

COPY requirements.txt .
RUN pip3 install -r requirements.txt

#COPY reddit_credentials.py .
COPY pol_sub.py .
COPY data_preprocessing.py .

CMD ["python", "data_preprocessing.py"]