version: '3'
services:
  reddit_streamer:
    build:
      context: ./Streaming
      dockerfile: Dockerfile.reddit_streamer
    volumes:
      - myvolume:/app/Shared

  data_preprocessing:
    build:
      context: ./Processing
      dockerfile: Dockerfile.data_preprocessing
    depends_on:
      - reddit_streamer
    ports:
      - 5000:5000
    volumes:
      - myvolume:/app/Shared

  front_streamlit:
    build:
      context: ./Streamlit
      dockerfile: Dockerfile.front_streamlit
    depends_on:
      - data_preprocessing
    ports:
      - 8501:8501
    volumes:
      - myvolume:/app/Shared
volumes:
  myvolume: