version: '3'
services:
  streamer:
    build:
      context: ./Streaming
      dockerfile: Dockerfile.streamer
    ports:
      - 8080:8080
    volumes:
      - myvolume:/app/Shared
    networks:
    - mynetwork
  data_preprocessing:
    build:
      context: ./Processing
      dockerfile: Dockerfile.data_preprocessing
    ports:
      - 5000:5000
    volumes:
      - myvolume:/app/Shared
    networks:
      - mynetwork
  front_streamlit:
    build:
      context: ./Streamlit
      dockerfile: Dockerfile.front_streamlit
    ports:
      - 8501:8501
    volumes:
      - myvolume:/app/Shared
    depends_on:
      - streamer
volumes:
  myvolume:
networks:
  mynetwork: