apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit
spec:
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
      - name: reddit
        image: emiliodallas/reddit_analysis:latest
---
apiVersion: v1
kind: Service
metadata:
  name: reddit-entrypoint
spec:
  type: NodePort
  selector:
    app: reddit
  ports:
  - port: 8501
    targetPort: 5000
    nodePort: 32001
